#include "effects/gfx/effect__26_MusicNote_DoubleBeam.png.inc.c"
#include "effects/gfx/effect__26_MusicNote_SingleBeam.png.inc.c"
#include "effects/gfx/effect__26_MusicNote_Eighth.png.inc.c"
#include "effects/gfx/effect__26_MusicNote_DottedQuarter.png.inc.c"
#include "effects/gfx/effect__26_MusicNote_Quarter.png.inc.c"
#include "effects/gfx/effect__26_MusicNote_DottedHalf.png.inc.c"
#include "effects/gfx/effect__26_MusicNote_Half.png.inc.c"

#include "effects/gfx/effect__26_MusicNote_DoubleBeam_Glow.png.inc.c"
#include "effects/gfx/effect__26_MusicNote_SingleBeam_Glow.png.inc.c"
#include "effects/gfx/effect__26_MusicNote_Eighth_Glow.png.inc.c"
#include "effects/gfx/effect__26_MusicNote_DottedQuarter_Glow.png.inc.c"
#include "effects/gfx/effect__26_MusicNote_Quarter_Glow.png.inc.c"
#include "effects/gfx/effect__26_MusicNote_DottedHalf_Glow.png.inc.c"
#include "effects/gfx/effect__26_MusicNote_Half_Glow.png.inc.c"

#include "effects/gfx/D_09000E00_35B3E0.vtx.inc.c"

#include "effects/gfx/D_09000FC0_35B5A0.gfx.inc.c"
#include "effects/gfx/D_09001038_35B618.gfx.inc.c"
#include "effects/gfx/D_090010C0_35B6A0.gfx.inc.c"
#include "effects/gfx/D_09001148_35B728.gfx.inc.c"
#include "effects/gfx/D_090011D0_35B7B0.gfx.inc.c"
#include "effects/gfx/D_09001258_35B838.gfx.inc.c"
#include "effects/gfx/D_090012E0_35B8C0.gfx.inc.c"
#include "effects/gfx/D_09001368_35B948.gfx.inc.c"
